# Github Actions do Site de perfil profissional.


name: Gatsby-Blog

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          access-token: ${{ secrets.DACIOLIMA_GATSBY_BLOG }}

